foreground         #F6ECDA
background         #1D1A19
cursor             #B7B6BA

active_tab_foreground     #1D1A19
active_tab_background     #F6ECDA
inactive_tab_foreground   #F6ECDA
inactive_tab_background   #1D1A19

active_border_color   #F6ECDA
inactive_border_color #1D1A19
bell_border_color     #9D827D

color0      #383332
color1		#9D827D
color2		#8087A0
color3		#9EA0A3
color4		#D49977
color5		#E0C3B7
color6		#E5C895
color7		#EADBC2
color8		#A39987
color9		#9D827D
color10		#8087A0
color11		#9EA0A3
color12		#D49977
color13		#E0C3B7
color14		#E5C895
color15		#EADBC2