foreground         #FDF5DC
background         #292424
cursor             #B59782

active_tab_foreground     #292424
active_tab_background     #FDF5DC
inactive_tab_foreground   #FDF5DC
inactive_tab_background   #292424

active_border_color   #FDF5DC
inactive_border_color #292424
bell_border_color     #6B5556

color0      #554F4F
color1		#6B5556
color2		#8E6559
color3		#B97B6A
color4		#F18D5C
color5		#FCC775
color6		#F8E29A
color7		#F3E8C4
color8		#AAA289
color9		#6B5556
color10		#8E6559
color11		#B97B6A
color12		#F18D5C
color13		#FCC775
color14		#F8E29A
color15		#F3E8C4