foreground         #EAF6F2
background         #1C201F
cursor             #ABC3B8

active_tab_foreground     #1C201F
active_tab_background     #EAF6F2
inactive_tab_foreground   #EAF6F2
inactive_tab_background   #1C201F

active_border_color   #EAF6F2
inactive_border_color #1C201F
bell_border_color     #708E82

color0      #464C4B
color1		#708E82
color2		#6C8F7E
color3		#8D9A75
color4		#A1B395
color5		#E5C273
color6		#C4E6DA
color7		#D9EAE4
color8		#98A4A0
color9		#708E82
color10		#6C8F7E
color11		#8D9A75
color12		#A1B395
color13		#E5C273
color14		#C4E6DA
color15		#D9EAE4