general {
    # Here we use `saturate` filter to have more vibrant colors,
    # not matter the scheme, since the border should seek the attention
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    resize_on_border = false
    allow_tearing = false
    layout = dwindle
    col.active_border = rgb(8C5194) rgb(8E6F63) rgb(A7548B) rgb(B053B6) rgb(DB42D9) rgb(F8D3F4)
    # color0 is almost the same as the background color,
    # by putting ee as the alpha, it makes it 100% transparent
    col.inactive_border = rgba(B053B6ee)
}
