general {
    # Here we use `saturate` filter to have more vibrant colors,
    # not matter the scheme, since the border should seek the attention
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    resize_on_border = false
    allow_tearing = false
    layout = dwindle
    col.active_border = rgb(9D827D) rgb(8087A0) rgb(9EA0A3) rgb(D49977) rgb(E0C3B7) rgb(E5C895)
    # color0 is almost the same as the background color,
    # by putting ee as the alpha, it makes it 100% transparent
    col.inactive_border = rgba(D49977ee)
}
