general {
    # Here we use `saturate` filter to have more vibrant colors,
    # not matter the scheme, since the border should seek the attention
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    resize_on_border = false
    allow_tearing = false
    layout = dwindle
    col.active_border = rgb(565766) rgb(8C6A78) rgb(6F899F) rgb(8A82A0) rgb(B5788F) rgb(D97F8F)
    # color0 is almost the same as the background color,
    # by putting ee as the alpha, it makes it 100% transparent
    col.inactive_border = rgba(8A82A0ee)
}
